version: '3.8'

services:
  db:
    build:
      context: /Budget App DB/database
    image: budget_management_db
    container_name: budget_management_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty33
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - budget_network  # Обязательно добавьте сюда

  app:
    build:
      context: /Budget App/
    image: budget_management_app
    container_name: budget_management_app
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwerty33
    depends_on:
      - db
    networks:
      - budget_network  # Убедитесь, что здесь указана та же сеть

volumes:
  db_data:

networks:
  budget_network:
    driver: bridge  # Используйте bridge-сеть
