version: '3.8'

services:
  db:
    build:
      context: /Budget App DB/database
    image: budget_management_db
    container_name: budget_management_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty33
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - budget_network  # Обязательно добавьте сюда

  registration:
    build:
      context: /Budget App Registration
    image: budget_management_registration
    container_name: budget_management_registration
    ports:
      - "25565:25565"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwerty33
    depends_on:
      - db
    networks:
      - budget_network

  transaction:
    build:
      context: /Budget App Transactions
    image: budget_management_transaction
    container_name: budget_management_transaction
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwerty33
    depends_on:
      - db
    networks:
      - budget_network

  frontend:
    build:
      context: /Budget App Frontend
    image: budget_management_frontend
    container_name: budget_management_frontend
    ports:
      - "3000:80"

volumes:
  db_data:

networks:
  budget_network:
    driver: bridge  # Используйте bridge-сеть
