version: '3.8'

services:
  db:
    build:
      context: ./database
    image: budget_management_db
    container_name: budget_management_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty33
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

