name: CI/CD for Front Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          
      - name: Test connection between front and registration
        run: |
          docker ps
          sleep 2  # Give services time to start
          docker exec  pad-budget-management-frontend-1 ping -c 3 pad-budget-management-registration-1
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./Budget App Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
